import type { DemoScenario } from '../types/cg.js'

export const AFFINE_SCENARIOS: Record<'2d' | '3d', DemoScenario[]> = {
  '2d': [
    {
      id: '2d-step-chain',
      mode: '2d',
      label: 'Step Chain',
      summary: 'A balanced translation-rotation-scale chain for explaining matrix order and intermediate shapes.',
      points: [
        [0, 40, 1],
        [14, 14, 1],
        [40, 8, 1],
        [20, -10, 1],
        [24, -38, 1],
        [0, -22, 1],
        [-24, -38, 1],
        [-20, -10, 1],
        [-40, 8, 1],
        [-14, 14, 1],
      ],
      localOrigin: [0, 0],
      transforms: [
        { type: 'translate', params: 'dx=80, dy=20' },
        { type: 'rotate', params: 'theta=30 deg' },
        { type: 'scale', params: 'sx=1.2, sy=0.9' },
      ],
    },
    {
      id: '2d-reflect-shear',
      mode: '2d',
      label: 'Reflect + Shear',
      summary: 'Highlights how reflection changes handedness before shear and translation reshape the figure.',
      points: [
        [-36, 26, 1],
        [-10, 30, 1],
        [18, 20, 1],
        [34, -6, 1],
        [4, -24, 1],
        [-22, -18, 1],
      ],
      localOrigin: [-8, 4],
      transforms: [
        { type: 'reflect', params: 'axis=y' },
        { type: 'shear', params: 'shx=0.45, shy=0' },
        { type: 'translate', params: 'dx=48, dy=-12' },
      ],
    },
    {
      id: '2d-local-frame',
      mode: '2d',
      label: 'Local Frame Story',
      summary: 'Moves a simple polygon away from the world frame so students can compare world and object-attached axes.',
      points: [
        [-18, 20, 1],
        [18, 20, 1],
        [28, -4, 1],
        [0, -26, 1],
        [-28, -4, 1],
      ],
      localOrigin: [6, -2],
      transforms: [
        { type: 'rotate', params: 'theta=35 deg' },
        { type: 'translate', params: 'dx=42, dy=18' },
      ],
    },
  ],
  '3d': [
    {
      id: '3d-cube-basics',
      mode: '3d',
      label: 'Cube Basics',
      summary: 'A clean translation-rotation-scale chain for the default cube, ideal for first-pass 3D narration.',
      points: [
        [-1, -1, -1, 1],
        [1, -1, -1, 1],
        [1, 1, -1, 1],
        [-1, 1, -1, 1],
        [-1, -1, 1, 1],
        [1, -1, 1, 1],
        [1, 1, 1, 1],
        [-1, 1, 1, 1],
      ],
      localOrigin: [0, 0, 0],
      transforms: [
        { type: 'translate', params: 'dx=0.8, dy=0.4, dz=-0.5' },
        { type: 'rotate', params: 'theta=20 deg, axis=y' },
        { type: 'scale', params: 'sx=1.1, sy=1.1, sz=0.8' },
      ],
    },
    {
      id: '3d-axis-tour',
      mode: '3d',
      label: 'Axis Tour',
      summary: 'Uses sequential rotations around x and z so students can narrate orientation change axis by axis.',
      points: [
        [-1, -1, -1, 1],
        [1, -1, -1, 1],
        [1, 1, -1, 1],
        [-1, 1, -1, 1],
        [-1, -1, 1, 1],
        [1, -1, 1, 1],
        [1, 1, 1, 1],
        [-1, 1, 1, 1],
      ],
      localOrigin: [0.25, -0.25, 0],
      transforms: [
        { type: 'rotate', params: 'theta=35 deg, axis=x' },
        { type: 'rotate', params: 'theta=30 deg, axis=z' },
        { type: 'translate', params: 'dx=0.9, dy=0.6, dz=-0.5' },
      ],
    },
    {
      id: '3d-point-cloud',
      mode: '3d',
      label: 'Point Cloud Sketch',
      summary: 'A non-cube point set for demonstrating why wireframe mode selection matters during teaching.',
      points: [
        [-1.4, -0.6, -0.8, 1],
        [0.2, -1.2, -0.2, 1],
        [1.3, -0.1, -1, 1],
        [-0.7, 1.1, -0.4, 1],
        [0.8, 1.3, 0.5, 1],
        [-1.1, 0.2, 1.2, 1],
      ],
      localOrigin: [0, 0, 0.2],
      transforms: [
        { type: 'scale', params: 'sx=1.2, sy=0.8, sz=1.1' },
        { type: 'rotate', params: 'theta=28 deg, axis=y' },
        { type: 'translate', params: 'dx=1, dy=1.6, dz=-0.8' },
      ],
    },
  ],
}
